#! /usr/bin/env gsi
;;(include "macros.scm")
(include "match.scm")
(include "prims.scm")
(include "environnement.scm")
(include "closure-conv.scm")
(include "hoisting.scm")
(include "intermediate.scm")
(include "codegen.scm")
(include "parser.scm")
(include "compiler.scm")
(include "cps.scm")